// Code generated by MockGen. DO NOT EDIT.
// Source: ./topology/topology.go
//
// Generated by this command:
//
//	mockgen -source=./topology/topology.go -destination=./topology/mock/topology.go
//

// Package mock_topology is a generated GoMock package.
package mock_topology

import (
	context "context"
	reflect "reflect"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	topology "github.com/sprintertech/sprinter-signing/topology"
	gomock "go.uber.org/mock/gomock"
)

// MockS3Client is a mock of S3Client interface.
type MockS3Client struct {
	ctrl     *gomock.Controller
	recorder *MockS3ClientMockRecorder
	isgomock struct{}
}

// MockS3ClientMockRecorder is the mock recorder for MockS3Client.
type MockS3ClientMockRecorder struct {
	mock *MockS3Client
}

// NewMockS3Client creates a new mock instance.
func NewMockS3Client(ctrl *gomock.Controller) *MockS3Client {
	mock := &MockS3Client{ctrl: ctrl}
	mock.recorder = &MockS3ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Client) EXPECT() *MockS3ClientMockRecorder {
	return m.recorder
}

// GetObject mocks base method.
func (m *MockS3Client) GetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetObject", varargs...)
	ret0, _ := ret[0].(*s3.GetObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockS3ClientMockRecorder) GetObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockS3Client)(nil).GetObject), varargs...)
}

// MockDecrypter is a mock of Decrypter interface.
type MockDecrypter struct {
	ctrl     *gomock.Controller
	recorder *MockDecrypterMockRecorder
	isgomock struct{}
}

// MockDecrypterMockRecorder is the mock recorder for MockDecrypter.
type MockDecrypterMockRecorder struct {
	mock *MockDecrypter
}

// NewMockDecrypter creates a new mock instance.
func NewMockDecrypter(ctrl *gomock.Controller) *MockDecrypter {
	mock := &MockDecrypter{ctrl: ctrl}
	mock.recorder = &MockDecrypterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecrypter) EXPECT() *MockDecrypterMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockDecrypter) Decrypt(data []byte) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", data)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockDecrypterMockRecorder) Decrypt(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockDecrypter)(nil).Decrypt), data)
}

// MockNetworkTopologyProvider is a mock of NetworkTopologyProvider interface.
type MockNetworkTopologyProvider struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkTopologyProviderMockRecorder
	isgomock struct{}
}

// MockNetworkTopologyProviderMockRecorder is the mock recorder for MockNetworkTopologyProvider.
type MockNetworkTopologyProviderMockRecorder struct {
	mock *MockNetworkTopologyProvider
}

// NewMockNetworkTopologyProvider creates a new mock instance.
func NewMockNetworkTopologyProvider(ctrl *gomock.Controller) *MockNetworkTopologyProvider {
	mock := &MockNetworkTopologyProvider{ctrl: ctrl}
	mock.recorder = &MockNetworkTopologyProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkTopologyProvider) EXPECT() *MockNetworkTopologyProviderMockRecorder {
	return m.recorder
}

// NetworkTopology mocks base method.
func (m *MockNetworkTopologyProvider) NetworkTopology(hash string) (*topology.NetworkTopology, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkTopology", hash)
	ret0, _ := ret[0].(*topology.NetworkTopology)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkTopology indicates an expected call of NetworkTopology.
func (mr *MockNetworkTopologyProviderMockRecorder) NetworkTopology(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkTopology", reflect.TypeOf((*MockNetworkTopologyProvider)(nil).NetworkTopology), hash)
}
