// Code generated by MockGen. DO NOT EDIT.
// Source: ./protocol/lifi/event.go
//
// Generated by this command:
//
//	mockgen -source=./protocol/lifi/event.go -destination=./protocol/lifi/mock/event.go
//

// Package mock_lifi is a generated GoMock package.
package mock_lifi

import (
	context "context"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockReceiptFetcher is a mock of ReceiptFetcher interface.
type MockReceiptFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockReceiptFetcherMockRecorder
	isgomock struct{}
}

// MockReceiptFetcherMockRecorder is the mock recorder for MockReceiptFetcher.
type MockReceiptFetcherMockRecorder struct {
	mock *MockReceiptFetcher
}

// NewMockReceiptFetcher creates a new mock instance.
func NewMockReceiptFetcher(ctrl *gomock.Controller) *MockReceiptFetcher {
	mock := &MockReceiptFetcher{ctrl: ctrl}
	mock.recorder = &MockReceiptFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReceiptFetcher) EXPECT() *MockReceiptFetcherMockRecorder {
	return m.recorder
}

// TransactionReceipt mocks base method.
func (m *MockReceiptFetcher) TransactionReceipt(ctx context.Context, txHash common.Hash) (*types.Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionReceipt", ctx, txHash)
	ret0, _ := ret[0].(*types.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionReceipt indicates an expected call of TransactionReceipt.
func (mr *MockReceiptFetcherMockRecorder) TransactionReceipt(ctx, txHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionReceipt", reflect.TypeOf((*MockReceiptFetcher)(nil).TransactionReceipt), ctx, txHash)
}
