package consts

import (
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi"
)

var RhinestoneABI, _ = abi.JSON(strings.NewReader(`
[
   {
      "type":"function",
      "name":"fill",
      "inputs":[
         {
            "name":"payload",
            "type":"tuple",
            "internalType":"struct IRhinestoneSpokePool.IntentFillPayload",
            "components":[
               {
                  "name":"segments",
                  "type":"tuple[]",
                  "internalType":"struct IRhinestoneSpokePool.SegmentData[]",
                  "components":[
                     {
                        "name":"tokenIn",
                        "type":"uint256[2][]",
                        "internalType":"uint256[2][]"
                     },
                     {
                        "name":"tokenOut",
                        "type":"uint256[2][]",
                        "internalType":"uint256[2][]"
                     },
                     {
                        "name":"originModule",
                        "type":"address",
                        "internalType":"address"
                     },
                     {
                        "name":"originWETHAddress",
                        "type":"address",
                        "internalType":"address"
                     },
                     {
                        "name":"originChainId",
                        "type":"uint256",
                        "internalType":"uint256"
                     },
                     {
                        "name":"compactNonce",
                        "type":"uint256",
                        "internalType":"uint256"
                     }
                  ]
               },
               {
                  "name":"message",
                  "type":"bytes",
                  "internalType":"bytes"
               },
               {
                  "name":"orchestratorSig",
                  "type":"bytes",
                  "internalType":"bytes"
               }
            ]
         },
         {
            "name":"exclusiveRelayer",
            "type":"address",
            "internalType":"address"
         },
         {
            "name":"repaymentAddresses",
            "type":"address[]",
            "internalType":"address[]"
         },
         {
            "name":"repaymentChainIds",
            "type":"uint256[]",
            "internalType":"uint256[]"
         },
         {
            "name":"accountCreation",
            "type":"tuple",
            "internalType":"AccountCreation ",
            "components":[
               {
                  "name":"account",
                  "type":"address",
                  "internalType":"address"
               },
               {
                  "name":"initCode",
                  "type":"bytes",
                  "internalType":"bytes"
               }
            ]
         }
      ],
      "outputs":[
         
      ],
      "stateMutability":"nonpayable"
   },
   {
      "type":"function",
      "name":"fill",
      "inputs":[
         {
            "name":"payload",
            "type":"tuple",
            "internalType":"struct IRhinestoneSpokePool.IntentFillPayload",
            "components":[
               {
                  "name":"segments",
                  "type":"tuple[]",
                  "internalType":"struct IRhinestoneSpokePool.SegmentData[]",
                  "components":[
                     {
                        "name":"tokenIn",
                        "type":"uint256[2][]",
                        "internalType":"uint256[2][]"
                     },
                     {
                        "name":"tokenOut",
                        "type":"uint256[2][]",
                        "internalType":"uint256[2][]"
                     },
                     {
                        "name":"originModule",
                        "type":"address",
                        "internalType":"address"
                     },
                     {
                        "name":"originWETHAddress",
                        "type":"address",
                        "internalType":"address"
                     },
                     {
                        "name":"originChainId",
                        "type":"uint256",
                        "internalType":"uint256"
                     },
                     {
                        "name":"compactNonce",
                        "type":"uint256",
                        "internalType":"uint256"
                     }
                  ]
               },
               {
                  "name":"message",
                  "type":"bytes",
                  "internalType":"bytes"
               },
               {
                  "name":"orchestratorSig",
                  "type":"bytes",
                  "internalType":"bytes"
               }
            ]
         },
         {
            "name":"exclusiveRelayer",
            "type":"address",
            "internalType":"address"
         },
         {
            "name":"repaymentAddresses",
            "type":"address[]",
            "internalType":"address[]"
         },
         {
            "name":"repaymentChainIds",
            "type":"uint256[]",
            "internalType":"uint256[]"
         }
      ],
      "outputs":[
         
      ],
      "stateMutability":"nonpayable"
   }
]
`))
