services:
  relayer1:
    image: ghcr.io/sprintertech/sprinter-signing:${SIGNING_IMAGE_VERSION}
    command: >
      mkdir -p /cfg/keyshares && 
      echo ${CONFIG_FULL} | base64 --decode > ${CONFIG_PATH} &&
      echo ${KEYSHARE} | base64 --decode > ${KEYSHARE_PATH} &&
      /signing run --config ${CONFIG_PATH} --staging
    entrypoint: ["/bin/sh", "-c"]
    environment:
      - CONFIG_FULL=${CONFIG_1_FULL}
      - KEYSHARE=${KEYSHARE_1}
      - CONFIG_PATH=/cfg/config_1.json
      - KEYSHARE_PATH=/cfg/keyshares/0.keyshare
      - VIRTUAL_HOST=signing.stage.sprinter.tech
    ports:
      - 3000:3000
    expose:
      - "3000"
    restart: always

  relayer2:
    image: ghcr.io/sprintertech/sprinter-signing:${SIGNING_IMAGE_VERSION}
    command: >
      mkdir -p /cfg/keyshares && 
      echo ${CONFIG_FULL} | base64 --decode > ${CONFIG_PATH} &&
      echo ${KEYSHARE} | base64 --decode > ${KEYSHARE_PATH} &&
      /signing run --config ${CONFIG_PATH} --staging
    entrypoint: ["/bin/sh", "-c"]
    environment:
      - CONFIG_FULL=${CONFIG_2_FULL}
      - KEYSHARE=${KEYSHARE_2}
      - CONFIG_PATH=/cfg/config_2.json
      - KEYSHARE_PATH=/cfg/keyshares/1.keyshare
    restart: always
    ports:
      - 3001:3000

  relayer3:
    image: ghcr.io/sprintertech/sprinter-signing:${SIGNING_IMAGE_VERSION}
    command: >
      mkdir -p /cfg/keyshares && 
      echo ${CONFIG_FULL} | base64 --decode > ${CONFIG_PATH} &&
      echo ${KEYSHARE} | base64 --decode > ${KEYSHARE_PATH} &&
      /signing run --config ${CONFIG_PATH} --staging
    entrypoint: ["/bin/sh", "-c"]
    environment:
      - CONFIG_FULL=${CONFIG_3_FULL}
      - KEYSHARE=${KEYSHARE_3}
      - CONFIG_PATH=/cfg/config_3.json
      - KEYSHARE_PATH=/cfg/keyshares/2.keyshare
    ports:
      - 3002:3000
    restart: always

# nginx automatically proxies exposed container ports
  nginx:
    image: jwilder/nginx-proxy:1.7.1
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
