services:
  relayer1:
    image: ghcr.io/sprintertech/sprinter-signing:${SIGNING_IMAGE_VERSION}
    command:
      - |
        mkdir -p /cfg/keyshares
        printenv KEYSHARE > "$${SYG_RELAYER_MPCCONFIG_KEYSHAREPATH}"
        /signing run --config env --staging
    entrypoint: ["/bin/sh", "-c"]
    environment:
      - SYG_RELAYER_MPCCONFIG_KEY=${SYG_RELAYER_MPCCONFIG_KEY_1}
      - SYG_RELAYER_MPCCONFIG_KEYSHAREPATH=/cfg/keyshares/0.keyshare
      - KEYSHARE=${KEYSHARE_1}
      - SYG_RELAYER_MPCCONFIG_PORT=9000
      - SYG_RELAYER_MPCCONFIG_COMMHEALTHCHECKINTERVAL=1h
      - SYG_RELAYER_LOGLEVEL=debug
      - SYG_CHAINS=${SYG_CHAINS}
      - SYG_RELAYER_SOLVERCONFIG_ACCESSKEY=${SYG_RELAYER_SOLVERCONFIG_ACCESSKEY}
      - SYG_RELAYER_SOLVERCONFIG_SECRETKEY=${SYG_RELAYER_SOLVERCONFIG_SECRETKEY}
      - SYG_RELAYER_COINMARKETCAPCONFIG_APIKEY=${SYG_RELAYER_COINMARKETCAPCONFIG_APIKEY}
      - SYG_RELAYER_MPCCONFIG_TOPOLOGYCONFIGURATION_ENCRYPTIONKEY=${SYG_RELAYER_MPCCONFIG_TOPOLOGYCONFIGURATION_ENCRYPTIONKEY}
      - SYG_RELAYER_MPCCONFIG_TOPOLOGYCONFIGURATION_URL=${SYG_RELAYER_MPCCONFIG_TOPOLOGYCONFIGURATION_URL}
      - SYG_RELAYER_MPCCONFIG_TOPOLOGYCONFIGURATION_PATH=topology-1
      - SYG_RELAYER_OPENTELEMETRYCOLLECTORURL=${SYG_RELAYER_OPENTELEMETRYCOLLECTORURL}
      - SYG_RELAYER_ENV=staging
      - SYG_RELAYER_ID=1
      - VIRTUAL_HOST=${SPRINTER_SIGNING_DOMAIN}
    labels:
      logging: "alloy"
      logging_jobname: "containerlogs"
      service_name: "signing_relayer_1_staging"
    ports:
      - 3000:3000
    expose:
      - "3000"
    restart: always

  relayer2:
    image: ghcr.io/sprintertech/sprinter-signing:${SIGNING_IMAGE_VERSION}
    command:
      - |
        mkdir -p /cfg/keyshares
        printenv KEYSHARE > "$${SYG_RELAYER_MPCCONFIG_KEYSHAREPATH}"
        /signing run --config env --staging
    entrypoint: ["/bin/sh", "-c"]
    environment:
      - SYG_RELAYER_MPCCONFIG_KEY=${SYG_RELAYER_MPCCONFIG_KEY_2}
      - SYG_RELAYER_MPCCONFIG_KEYSHAREPATH=/cfg/keyshares/1.keyshare
      - KEYSHARE=${KEYSHARE_2}
      - SYG_RELAYER_MPCCONFIG_PORT=9000
      - SYG_RELAYER_MPCCONFIG_COMMHEALTHCHECKINTERVAL=1h
      - SYG_RELAYER_LOGLEVEL=debug
      - SYG_CHAINS=${SYG_CHAINS}
      - SYG_RELAYER_SOLVERCONFIG_ACCESSKEY=${SYG_RELAYER_SOLVERCONFIG_ACCESSKEY}
      - SYG_RELAYER_SOLVERCONFIG_SECRETKEY=${SYG_RELAYER_SOLVERCONFIG_SECRETKEY}
      - SYG_RELAYER_COINMARKETCAPCONFIG_APIKEY=${SYG_RELAYER_COINMARKETCAPCONFIG_APIKEY}
      - SYG_RELAYER_MPCCONFIG_TOPOLOGYCONFIGURATION_ENCRYPTIONKEY=${SYG_RELAYER_MPCCONFIG_TOPOLOGYCONFIGURATION_ENCRYPTIONKEY}
      - SYG_RELAYER_MPCCONFIG_TOPOLOGYCONFIGURATION_URL=${SYG_RELAYER_MPCCONFIG_TOPOLOGYCONFIGURATION_URL}
      - SYG_RELAYER_MPCCONFIG_TOPOLOGYCONFIGURATION_PATH=topology-2
      - SYG_RELAYER_OPENTELEMETRYCOLLECTORURL=${SYG_RELAYER_OPENTELEMETRYCOLLECTORURL}
      - SYG_RELAYER_ENV=staging
      - SYG_RELAYER_ID=2
    labels:
      logging: "alloy"
      logging_jobname: "containerlogs"
      service_name: "signing_relayer_2_staging"
    ports:
      - 3001:3000
    restart: always

  relayer3:
    image: ghcr.io/sprintertech/sprinter-signing:${SIGNING_IMAGE_VERSION}
    command:
      - |
        mkdir -p /cfg/keyshares
        printenv KEYSHARE > "$${SYG_RELAYER_MPCCONFIG_KEYSHAREPATH}"
        /signing run --config env --staging
    entrypoint: ["/bin/sh", "-c"]
    environment:
      - SYG_RELAYER_MPCCONFIG_KEY=${SYG_RELAYER_MPCCONFIG_KEY_3}
      - SYG_RELAYER_MPCCONFIG_KEYSHAREPATH=/cfg/keyshares/2.keyshare
      - KEYSHARE=${KEYSHARE_3}
      - SYG_RELAYER_MPCCONFIG_PORT=9000
      - SYG_RELAYER_MPCCONFIG_COMMHEALTHCHECKINTERVAL=1h
      - SYG_RELAYER_LOGLEVEL=debug
      - SYG_CHAINS=${SYG_CHAINS}
      - SYG_RELAYER_SOLVERCONFIG_ACCESSKEY=${SYG_RELAYER_SOLVERCONFIG_ACCESSKEY}
      - SYG_RELAYER_SOLVERCONFIG_SECRETKEY=${SYG_RELAYER_SOLVERCONFIG_SECRETKEY}
      - SYG_RELAYER_COINMARKETCAPCONFIG_APIKEY=${SYG_RELAYER_COINMARKETCAPCONFIG_APIKEY}
      - SYG_RELAYER_MPCCONFIG_TOPOLOGYCONFIGURATION_ENCRYPTIONKEY=${SYG_RELAYER_MPCCONFIG_TOPOLOGYCONFIGURATION_ENCRYPTIONKEY}
      - SYG_RELAYER_MPCCONFIG_TOPOLOGYCONFIGURATION_URL=${SYG_RELAYER_MPCCONFIG_TOPOLOGYCONFIGURATION_URL}
      - SYG_RELAYER_MPCCONFIG_TOPOLOGYCONFIGURATION_PATH=topology-3
      - SYG_RELAYER_OPENTELEMETRYCOLLECTORURL=${SYG_RELAYER_OPENTELEMETRYCOLLECTORURL}
      - SYG_RELAYER_ENV=staging
      - SYG_RELAYER_ID=3
    labels:
      logging: "alloy"
      logging_jobname: "containerlogs"
      service_name: "signing_relayer_3_staging"
    ports:
      - 3002:3000
    restart: always

# nginx automatically proxies exposed container ports
  nginx:
    image: jwilder/nginx-proxy:1.7.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/ssl:/etc/nginx/certs
    restart: unless-stopped
