// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/handlers/signing.go
//
// Generated by this command:
//
//	mockgen -source=./api/handlers/signing.go -destination=./api/handlers/mock/signing.go
//

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSignatureCacher is a mock of SignatureCacher interface.
type MockSignatureCacher struct {
	ctrl     *gomock.Controller
	recorder *MockSignatureCacherMockRecorder
	isgomock struct{}
}

// MockSignatureCacherMockRecorder is the mock recorder for MockSignatureCacher.
type MockSignatureCacherMockRecorder struct {
	mock *MockSignatureCacher
}

// NewMockSignatureCacher creates a new mock instance.
func NewMockSignatureCacher(ctrl *gomock.Controller) *MockSignatureCacher {
	mock := &MockSignatureCacher{ctrl: ctrl}
	mock.recorder = &MockSignatureCacherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignatureCacher) EXPECT() *MockSignatureCacherMockRecorder {
	return m.recorder
}

// Subscribe mocks base method.
func (m *MockSignatureCacher) Subscribe(ctx context.Context, id string, sigChannel chan []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Subscribe", ctx, id, sigChannel)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockSignatureCacherMockRecorder) Subscribe(ctx, id, sigChannel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockSignatureCacher)(nil).Subscribe), ctx, id, sigChannel)
}

// MockSignatureRemover is a mock of SignatureRemover interface.
type MockSignatureRemover struct {
	ctrl     *gomock.Controller
	recorder *MockSignatureRemoverMockRecorder
	isgomock struct{}
}

// MockSignatureRemoverMockRecorder is the mock recorder for MockSignatureRemover.
type MockSignatureRemoverMockRecorder struct {
	mock *MockSignatureRemover
}

// NewMockSignatureRemover creates a new mock instance.
func NewMockSignatureRemover(ctrl *gomock.Controller) *MockSignatureRemover {
	mock := &MockSignatureRemover{ctrl: ctrl}
	mock.recorder = &MockSignatureRemoverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignatureRemover) EXPECT() *MockSignatureRemoverMockRecorder {
	return m.recorder
}

// Remove mocks base method.
func (m *MockSignatureRemover) Remove(id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", id)
}

// Remove indicates an expected call of Remove.
func (mr *MockSignatureRemoverMockRecorder) Remove(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockSignatureRemover)(nil).Remove), id)
}
