// Code generated by MockGen. DO NOT EDIT.
// Source: ./tss/coordinator.go
//
// Generated by this command:
//
//	mockgen -source=./tss/coordinator.go -destination=./tss/mock/coordinator.go
//

// Package mock_tss is a generated GoMock package.
package mock_tss

import (
	context "context"
	reflect "reflect"
	time "time"

	peer "github.com/libp2p/go-libp2p/core/peer"
	gomock "go.uber.org/mock/gomock"
)

// MockTssProcess is a mock of TssProcess interface.
type MockTssProcess struct {
	ctrl     *gomock.Controller
	recorder *MockTssProcessMockRecorder
	isgomock struct{}
}

// MockTssProcessMockRecorder is the mock recorder for MockTssProcess.
type MockTssProcessMockRecorder struct {
	mock *MockTssProcess
}

// NewMockTssProcess creates a new mock instance.
func NewMockTssProcess(ctrl *gomock.Controller) *MockTssProcess {
	mock := &MockTssProcess{ctrl: ctrl}
	mock.recorder = &MockTssProcessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTssProcess) EXPECT() *MockTssProcessMockRecorder {
	return m.recorder
}

// Ready mocks base method.
func (m *MockTssProcess) Ready(readyPeers, excludedPeers []peer.ID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ready", readyPeers, excludedPeers)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ready indicates an expected call of Ready.
func (mr *MockTssProcessMockRecorder) Ready(readyPeers, excludedPeers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ready", reflect.TypeOf((*MockTssProcess)(nil).Ready), readyPeers, excludedPeers)
}

// Retryable mocks base method.
func (m *MockTssProcess) Retryable() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retryable")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Retryable indicates an expected call of Retryable.
func (mr *MockTssProcessMockRecorder) Retryable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retryable", reflect.TypeOf((*MockTssProcess)(nil).Retryable))
}

// Run mocks base method.
func (m *MockTssProcess) Run(ctx context.Context, coordinator bool, resultChn chan any, params []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, coordinator, resultChn, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockTssProcessMockRecorder) Run(ctx, coordinator, resultChn, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockTssProcess)(nil).Run), ctx, coordinator, resultChn, params)
}

// SessionID mocks base method.
func (m *MockTssProcess) SessionID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionID")
	ret0, _ := ret[0].(string)
	return ret0
}

// SessionID indicates an expected call of SessionID.
func (mr *MockTssProcessMockRecorder) SessionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionID", reflect.TypeOf((*MockTssProcess)(nil).SessionID))
}

// StartParams mocks base method.
func (m *MockTssProcess) StartParams(readyPeers []peer.ID) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartParams", readyPeers)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// StartParams indicates an expected call of StartParams.
func (mr *MockTssProcessMockRecorder) StartParams(readyPeers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartParams", reflect.TypeOf((*MockTssProcess)(nil).StartParams), readyPeers)
}

// Stop mocks base method.
func (m *MockTssProcess) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockTssProcessMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockTssProcess)(nil).Stop))
}

// Timeout mocks base method.
func (m *MockTssProcess) Timeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Timeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Timeout indicates an expected call of Timeout.
func (mr *MockTssProcessMockRecorder) Timeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Timeout", reflect.TypeOf((*MockTssProcess)(nil).Timeout))
}

// ValidCoordinators mocks base method.
func (m *MockTssProcess) ValidCoordinators() []peer.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidCoordinators")
	ret0, _ := ret[0].([]peer.ID)
	return ret0
}

// ValidCoordinators indicates an expected call of ValidCoordinators.
func (mr *MockTssProcessMockRecorder) ValidCoordinators() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidCoordinators", reflect.TypeOf((*MockTssProcess)(nil).ValidCoordinators))
}

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// EndProcess mocks base method.
func (m *MockMetrics) EndProcess(sessionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EndProcess", sessionID)
}

// EndProcess indicates an expected call of EndProcess.
func (mr *MockMetricsMockRecorder) EndProcess(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndProcess", reflect.TypeOf((*MockMetrics)(nil).EndProcess), sessionID)
}

// StartProcess mocks base method.
func (m *MockMetrics) StartProcess(sessionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartProcess", sessionID)
}

// StartProcess indicates an expected call of StartProcess.
func (mr *MockMetricsMockRecorder) StartProcess(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartProcess", reflect.TypeOf((*MockMetrics)(nil).StartProcess), sessionID)
}
