// Code generated by MockGen. DO NOT EDIT.
// Source: ./chains/evm/message/unlock.go
//
// Generated by this command:
//
//	mockgen -source=./chains/evm/message/unlock.go -destination=./chains/evm/message/mock/unlock.go
//

// Package mock_message is a generated GoMock package.
package mock_message

import (
	reflect "reflect"

	order "github.com/sprintertech/solver-sdk/pkg/order"
	lifi "github.com/sprintertech/solver-sdk/pkg/protocols/lifi"
	token "github.com/sprintertech/solver-sdk/pkg/token"
	gomock "go.uber.org/mock/gomock"
)

// MockLifiAPI is a mock of LifiAPI interface.
type MockLifiAPI struct {
	ctrl     *gomock.Controller
	recorder *MockLifiAPIMockRecorder
	isgomock struct{}
}

// MockLifiAPIMockRecorder is the mock recorder for MockLifiAPI.
type MockLifiAPIMockRecorder struct {
	mock *MockLifiAPI
}

// NewMockLifiAPI creates a new mock instance.
func NewMockLifiAPI(ctrl *gomock.Controller) *MockLifiAPI {
	mock := &MockLifiAPI{ctrl: ctrl}
	mock.recorder = &MockLifiAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLifiAPI) EXPECT() *MockLifiAPIMockRecorder {
	return m.recorder
}

// GetOrder mocks base method.
func (m *MockLifiAPI) GetOrder(orderID string) (*lifi.LifiOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", orderID)
	ret0, _ := ret[0].(*lifi.LifiOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockLifiAPIMockRecorder) GetOrder(orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockLifiAPI)(nil).GetOrder), orderID)
}

// MockTokenResolver is a mock of TokenResolver interface.
type MockTokenResolver struct {
	ctrl     *gomock.Controller
	recorder *MockTokenResolverMockRecorder
	isgomock struct{}
}

// MockTokenResolverMockRecorder is the mock recorder for MockTokenResolver.
type MockTokenResolverMockRecorder struct {
	mock *MockTokenResolver
}

// NewMockTokenResolver creates a new mock instance.
func NewMockTokenResolver(ctrl *gomock.Controller) *MockTokenResolver {
	mock := &MockTokenResolver{ctrl: ctrl}
	mock.recorder = &MockTokenResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenResolver) EXPECT() *MockTokenResolverMockRecorder {
	return m.recorder
}

// Token mocks base method.
func (m *MockTokenResolver) Token(caipID order.ChainCAIP, address [32]byte) (token.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token", caipID, address)
	ret0, _ := ret[0].(token.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Token indicates an expected call of Token.
func (mr *MockTokenResolverMockRecorder) Token(caipID, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockTokenResolver)(nil).Token), caipID, address)
}
