name: Publish Test Docker Image

permissions:
  packages: write
  contents: read

on:
  push:
    branches:
      - test

env:
  GO111MODULE: on
  GOPRIVATE: github.com/sprintertech
  ORG: 'sprintertech'
  REGISTRY: 'ghcr.io'
  TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup git access to private repos
        run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/sprintertech/".insteadOf "https://github.com/sprintertech/"

      # Log in to GHCR
      - name: Log in to GHCR
        id: ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Pass build arguments for the GitHub credentials
          secrets: |
            GH_USER_NAME=${{ secrets.GH_USER_NAME }}
            GH_USER_TOKEN=${{ secrets.GHCR_TOKEN }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:test
