# The Licensed Work is (c) 2022 Sygma
# SPDX-License-Identifier: LGPL-3.0-only

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GO111MODULE: on
  GOPRIVATE: github.com/sprintertech
  TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: Unit tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x]
        platform: [ ubuntu-latest ]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v5
      - id: go-cache-paths
        run: |
          echo "GO_BUILD=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"
          echo "GO_MOD=$(go env GOMODCACHE)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v4
        with:
          path: |
            ${{ steps.go-cache-paths.outputs.GO_BUILD }}
            ${{ steps.go-cache-paths.outputs.GO_MOD }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: setup git access to private repos
        run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/sprintertech/".insteadOf "https://github.com/sprintertech/"
      - name: Unit tests
        run: make test
      - name: Cover
        run:  echo "COVER=$(go tool cover -func cover.out | grep total | awk '{print substr($3, 1, length($3)-1)}')" >> $GITHUB_ENV
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.number}}
          body: |
            Go Test coverage is ${{env.COVER}} %\ :sparkles: :sparkles: :sparkles:
